apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-workspace
  namespace: quarkus-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi