apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: acs-image-scan
  namespace: quarkus-pipeline
spec:
  params:
    - name: rhacs-api-config-secret-name
      description: Secret containing the api-token and host data for ACS Central (example - api-token = <apitoken>, host = <rox.stackrox.io>)
      type: string
    - name: image_location
      description: Location of the image to be scanned
      type: string
  steps:
    - name: rox-deployment-check
      env:
        - name: ROX_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: acs_api_token
              name: $(params.rhacs-api-config-secret-name)
        - name: ROX_CENTRAL_HOST
          valueFrom:
            secretKeyRef:
              key: acs_central_endpoint
              name: $(params.rhacs-api-config-secret-name)
      image: registry.redhat.io/ubi8/ubi:8.5-226
      resources: {}
      script: >-
        #!/usr/bin/env bash

        curl -s -L -k -H 'Authorization: Bearer '$ROX_API_TOKEN
        'https://'$ROX_CENTRAL_HOST'/api/cli/download/roxctl-linux'
        --output ./roxctl

        chmod +x ./roxctl
        
        ./roxctl -e "https://$ROX_CENTRAL_HOST:443" image scan --image $(params.image_location) -o table

      workingDir: /workspace